export type CaptainsRow = {
  id: number;
  sno: number;
  firstName: string;
  lastName: string;
  phone: string;
  email: string | null;
  city: string;
  area: string | null;
  pincode: string | null;
  serviceCategory: string;
  vehicleType: string;
  vehicleSubType: string | null;
  fuelType: string;
  tripPreference: string;
  vehicleNumber: string;
  rcNumber: string;
  rcExpiry: string | null;
  insuranceNumber: string | null;
  insuranceExpiry: string | null;
  pucNumber: string | null;
  pucExpiry: string | null;
  fitnessNumber: string | null;
  fitnessExpiry: string | null;
  permitNumber: string | null;
  permitExpiry: string | null;
  dlNumber: string;
  dlExpiry: string | null;
  idProofType: string;
  idProofNumber: string | null;
  bundleTypes: string | null;
  bundleDiscount: number | null;
  rentalVehiclePref: string | null;
  rentalDuration: string | null;
  rentalPickupZone: string | null;
  driverHireCount: number | null;
  driverHireShift: string | null;
  driverHireBudget: string | null;
  additionalVehicles: string | null;
  parcelComboTypes: string | null;
  parcelMaxWeight: string | null;
  parcelRadiusPref: string | null;
  cargoCoRideMax: number | null;
  cargoCoRideHaulPref: string | null;
  cargoCoRideRatePref: string | null;
  accessFromDate: string | null;
  accessToDate: string | null;
  status: string;
  adminNotes: string | null;
  submittedAt: string | null;
  createdAt: string;
};

export type ActionType = 'approve' | 'reject';
